name: Build and Deploy React App

on:
  push:
    branches:
      - main # Change this to your main branch name
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install Dependencies
      run: |
        cd todo
        npm install

    - name: Build React App
      run: |
        cd todo
        npm run build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: 'todo/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
